/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackqueue;

public class Main {

    public static void main(String[] args) {

        XmlReader myXmlReader = new XmlReader("data.xml");

        // Queue operations
//        OrderQueue orders = myXmlReader.getOrders(); // Uncomment for testing
//        Order firstOrder = orders.dequeue();
//        System.out.println("DEQUEUE: " + firstOrder.getOrderNumber());
//        if (orders.peek() != null) {
//            System.out.println("PEEK: " + orders.peek().getOrderNumber());
//        }

        // Stack operations
//        ProductStack products = myXmlReader.getProducts(); // Uncomment for testing
//        Product firstProduct = products.pop();
//        System.out.println("POP: " + firstProduct.values());
//        if (products.peek() != null) {
//            System.out.println("PEEK: " + products.peek().values());
//        }
    }
}
