/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

public class Main {
    public static void main(String[] args) {

        XmlReader myXmlReader = new XmlReader("products.xml");

        // Get the product list
        ProductList productList = myXmlReader.getProducts();


        // Show the size of the list
        //System.out.println("Size: " + productList.size()); // Uncomment when ready to test

        // Show the sum of all the unit prices
        //System.out.println("Sum: " + productList.sum()); // Uncomment when ready to test

        // String representation of the list
        //System.out.println("---=== Product List ===---");
        //System.out.println(productList.head.toString());
        //System.out.println(productList.head.next.toString());
        System.out.println(productList.toString()); // Uncomment when ready to test
        System.out.println();
    }
}
